<?php

/**
 * Implements hook_ENTITY_TYPE_view_alter().
 */
function acsauth_user_view_alter(array &$build, Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display) {
  if ($build['#view_mode'] == 'full') {
    $info = "Account is not connected through ACS.";
    if (acsauth_acsid_load($entity->id()) !== FALSE) {
      $info = "Account is connected through ACS.";
    }

    $build['acsauth_connectinfo'] = array(
      '#markup' => t($info)
    );
  }
}

/**
 * Load an ACS ID given a Drupal User ID.
 */
function acsauth_acsid_load($uid = NULL) {
  $uid = isset($uid) ? $uid : \Drupal::currentUser()->id;
  $result = db_query("SELECT acsid FROM {acsauth_users} WHERE uid = :uid", array(
    ':uid' => $uid
  ));
  $acsid = $result->fetchField();
  return $acsid ? $acsid : FALSE;
}

/**
 * Load a Drupal User ID given an ACS ID.
 */
function acsauth_uid_load($acsid) {
  $result = db_query("SELECT uid FROM {acsauth_users} WHERE acsid = :acsid", array(
    ':acsid' => $acsid
  ));
  $uid = $result->fetchField();
  return $uid ? (int) $uid : FALSE;
}
